### ISSUE TITLE
Create page or section detailing resources in locked cabinets available for use

### ISSUE THREAD

**Issue by Hardolaf** [ElectronicsOSU/electronicsosu.github.io#28]
We need a page where we can list what resources are available in a locked, officer-only cabinet that we have for the club. We will ultimately provide images/details and a full list of what is available in the cabinet. But for now, if a page could be created with the three following items as samples that would be extremely useful

* HP 3310A (count 2)
* Arduino Due (count 1)
* Hakko FX888-D (count 1)

We need for every item:

* Name of item
* Count of item
* Picture of item (if available)
* Short description of item (function and typical use cases)
* Link to documentation on the item (datasheet, official product page, etc.)

I have no particular desire on how it should all be formatted or laid out, however, some sort of logical arrangement should be created.

The types of supplies that will be in this cabinet include:

* Function generators
* Bench power supplies
* Evaluation/Development kits
* Microcontroller boards
* Temperature controlled soldering stations

In addition to this, we need to have a section at the top describing the method and procedure for requesting an item from the cabinet and for returning an item to the cabinet. We will have these rules for you shortly (it is being written tomorrow, Oct. 30th at an officer's meeting).

**Comment by egladman** [comment]
not relevant at this time
