### ISSUE TITLE
update lab access policy under "Membership"

### ISSUE THREAD

**Issue by egladman** [ElectronicsOSU/electronicsosu.github.io#67]

**Comment by haestrod** [comment]
Electronics Club is easy to join, not to mention free. Subscribe to our mailing list and attend our next meeting. Active members can rent tools, take components for projects, and submit to the resume database. Active membership status is a semester-long condition found by attending at least two workshops per semester or volunteering for E-Council events in the club's name. Members who are interested are welcome to take on a leadership role by leading workshops or talks and are allowed 24/7 lab room access.

**Comment by egladman** [comment]
fixed - 8bd87185e61ba992f6de4205d9d2e6d6156f7eed
